### ISSUE TITLE
taskmanager

### ISSUE THREAD

**Issue by ghui9087** [turtiustrek/taskmanager#1]
where is the injector.exe file

**Comment by ghui9087** [comment]
sorry but what do you meaning when Compiling mingw32-make.exe  just copy that in to the CMD?

**Comment by turtiustrek** [comment]
the compiled binaries (injector.exe and dllmain.dll) are not included in the repository and you have to compile them on your own since you have to select some config parameters in the source code.
> sorry but what do you meaning when Compiling mingw32-make.exe just copy that in to the CMD?

Yes, so as the other commands but you will need to setup mingw-64 properly **or** use MYSYS2 shell to install this

MSYS2:

Here is a tutorial which can help you to install mingw-64 for MSYS2. 
https://www.youtube.com/watch?v=aXF4A5UeSeM

```git``` can be installed like this(run this after installing mingw-64 in msys2.exe):  ``` pacman -S git```
and then ```make``` can be installed like this(run this  in msys2.exe) ``` pacman -S make``` 

after that launch ```mingw64.exe``` and execute the following commands:
```
git clone --recurse-submodules  https://github.com/turtiustrek/taskmanager
cd taskmanager
make
```
you can find where the directory is by running the following command after running the commands above ```cygpath -m ~```

**Comment by ghui9087** [comment]
thank you so much
