### ISSUE TITLE
Cannot run mingw32-make.exe 

### ISSUE THREAD

**Issue by robloxboy24** [turtiustrek/taskmanager#5]
I cannot run `mingw32-make.exe ` for some reason

**Comment by robloxboy24** [comment]
It says its not a command

**Comment by turtiustrek** [comment]
because you have to setup both mingw-64 and git. 


Here is a tutorial which can help you to install mingw-64 for MSYS2. 
https://www.youtube.com/watch?v=aXF4A5UeSeM

```git``` can be installed like this(run this after installing mingw-64 in msys2.exe):  ``` pacman -S git```
and then ```make``` can be installed like this(run this  in msys2.exe) ``` pacman -S make``` 

after that launch ```mingw64.exe``` and execute the following commands:
```
git clone --recurse-submodules  https://github.com/turtiustrek/taskmanager
cd taskmanager
make
```
you can find where the directory is by running the following command after running the commands above ```cygpath -m ~```

**Comment by robloxboy24** [comment]
okay. I already installed git, I will try the tutorial now.

**Comment by robloxboy24** [comment]
It's still too hard for me. Can you record a video on how, please?

**Comment by turtiustrek** [comment]
Yes, ill also release a compiled binary along with it in the releases tab

**Comment by robloxboy24** [comment]
Okay. Thank you.

**Comment by turtiustrek** [comment]
added a release here:
https://github.com/turtiustrek/taskmanager/releases/tag/0.1
